### ISSUE TITLE
Определение окрестности бесконечности

### ISSUE THREAD

**Issue by Nna2291** [zhikh23/iu7-qa#1]
# Вопрос 3 и 4

Опираясь на конспекты фн12, определение окрестности +inf и -inf звучит немного по другому, душнота конечно та еще, но математика вообще ультра душная наука....
![image](https://github.com/zhikh23/iu7-rc/assets/66004120/9dca60e2-f82e-4202-9f24-4d660cf1436d)

**Comment by Nna2291** [comment]
В 5 вопросе тоже самое вроде, убери a>0

**Comment by zhikh23** [comment]
Да, тут интересно: на лекции, помню, было для положительных `a`, а тут вот оно как.
На лекции, на вопрос "почему `a` должно быть больше нуля", был дан ответ, что _окрестность не должна пересекать точку ноль_.
Так что предлагаю подойти в пятницу и спросить.
P.S. Думаю на РК настолько душнить не будут) и у нас с обеих сторон есть аргументы, что выбранный нами вариант верный: если мы пишем для `a > 0`, то можем показать конспекты, где записано именно это определение; если же запишем иначе, то можно показать конспекты ФН, которые еще более надёжный источник.

**Comment by Nna2291** [comment]
Напишу ей на почту через часик, думаю она даже помнит меня, она у нас семинарист

**Comment by zhikh23** [comment]
итак, РК кончился, закрываю
